---

driver_config:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /sbin/init
  provision_command:
    - apt-get install -y libffi-dev libssl-dev libyaml-cpp-dev apt-transport-https
    - apt-get install -y python python-dev python-pip python-setuptools git build-essential
    - pip install pip --upgrade -qqq
    - pip install setuptools paramiko pycparser pycrypto --upgrade -qqq
    - "pip install ansible==<%= ENV['ANSIBLE_INSTALL_VERSION'] || '2.1.4.0' %> --upgrade -qqq"

transport:
  connection_timeout: 120
  forward_agent: true
  max_ssh_sessions: 5

provisioner:
  ansible_verbose: true
  ansible_verbosity: 2
  extra_vars:
    test_mode: yes
  hosts: test-kitchen
  name: ansible_playbook
  # Ansible is already installed in our base image
  # skip reinstall to save time
  require_ansible_omnibus: false
  require_ansible_repo: false
  require_ansible_source: false
  require_chef_for_busser: false
  require_pip: false
  require_ruby_for_busser: false
  sudo_command: "sudo -HE"

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: solita/ubuntu-systemd:16.04
      run_options: '--security-opt seccomp=unconfined --stop-signal=SIGRTMIN+3 --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro'

  - name: ubuntu-14.04
    driver_config:
      image: ubuntu-upstart:14.04
      disable_upstart: false

suites:
  - name: default
