---

- name: Test PDM Mailserver Role
  hosts: all

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build

  roles:
    - role: lobsterdore.pdm-mailserver
      become: yes

