---
#
# Autoconfig XML file for email clients
# https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration
#

- name: Create directory for mail autoconfiguration virtualhost
  file:
    state: directory
    path: /var/www/autoconfig
    group: www-data
    owner: root

- name: Create directory holding the autoconfig XML file
  file:
    state: directory
    path: /var/www/autoconfig/mail
    group: www-data
    owner: root

- name: Create the autoconfig XML file
  template:
    src: var_www_autoconfig_mail_config-v1.1.j2
    dest: /var/www/autoconfig/mail/config-v1.1.xml
    group: www-data
    owner: root

- name: Create autoconfig site
  template:
    src: etc_nginx_autoconfig.conf.j2
    dest: /etc/nginx/sites-available/autoconfig.conf
  notify:
    - restart nginx

- name: Enable autoconfig site
  file:
    src: /etc/nginx/sites-available/autoconfig.conf
    dest: /etc/nginx/sites-enabled/autoconfig.conf
    state: link
  notify:
    - restart nginx
