---

- name: Add vhost directories
  file:
    group: vmail
    owner: vmail
    path: "/var/mail/vhosts/{{ item }}"
    state: directory
  with_items: "{{ pdm_mailserver_virtual_domains }}"

- name: Looks for extra MySQL settings
  stat:
    path: /etc/mysql/conf.d/custom.cnf
  register: custom_cnf
  when: pdm_mailserver_mysql_install_server

- name: Remove anonymous user
  mysql_user:
    login_host: localhost
    login_user: "{{ pdm_mailserver_mysql_root_user }}"
    login_password: ""
    name: ""
    state: absent
  when: not custom_cnf.stat.exists and
    pdm_mailserver_mysql_install_server

- name: Configure local MySQL root user password
  mysql_user:
    login_host: localhost
    login_user: "{{ pdm_mailserver_mysql_root_user }}"
    login_password: ""
    name: root
    password: "{{ pdm_mailserver_mysql_root_password }}"
    state: present
  when: not custom_cnf.stat.exists and
    pdm_mailserver_mysql_install_server

- name: Configure cusom MySQL client options
  template:
    src: mysql/custom.cnf.j2
    dest: /etc/mysql/conf.d/custom.cnf
  notify:
    - restart mysql
  when: pdm_mailserver_mysql_install_server

- name: Create database structure file
  template:
    dest: /tmp/db_structure.sql
    src: mysql/db_structure.sql.j2

- name: Create database
  mysql_db:
    name: "{{ pdm_mailserver_mysql_database }}"
    state: present
    login_host: "{{ pdm_mailserver_mysql_host }}"
    login_user: "{{ pdm_mailserver_mysql_root_user }}"
    login_password: "{{ pdm_mailserver_mysql_root_password }}"
  notify:
    - import database

- name: Create database user
  mysql_user:
    name: "{{ pdm_mailserver_mysql_user }}"
    password: "{{ pdm_mailserver_mysql_password }}"
    priv: "{{ pdm_mailserver_mysql_database }}.*:ALL"
    host: "%"
    state: present
    login_host: "{{ pdm_mailserver_mysql_host }}"
    login_user: "{{ pdm_mailserver_mysql_root_user }}"
    login_password: "{{ pdm_mailserver_mysql_root_password }}"

- name: Create mailname
  template:
    dest: /etc/mailname
    src: postfix/mailname.j2
  notify:
    - restart postfix

- name: Create postfix configs
  template:
    dest: "/etc/postfix/{{ item }}"
    src: "postfix/{{ item }}.j2"
  notify:
    - restart postfix
  with_items:
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-email2email.cf
    - master.cf

- name: Create dovecot configs
  template:
    owner: vmail
    group: dovecot
    mode: 0700
    dest: "/etc/dovecot/{{ item }}"
    src: "dovecot/{{ item }}.j2"
  notify:
    - restart dovecot
  with_items:
    - dovecot.conf
    - conf.d/10-mail.conf
    - conf.d/10-auth.conf
    - conf.d/auth-sql.conf.ext
    - dovecot-sql.conf.ext
    - conf.d/10-master.conf
    - conf.d/10-ssl.conf

- name: Update /etc/dovecot permissions
  file:
    group: dovecot
    mode: 0700
    owner: vmail
    path: /etc/dovecot
    state: directory
