---

- name: Ensure some repository keys
  apt_key:
    id: "{{ item }}"
    keyserver: hkps.pool.sks-keyservers.net
    state: present
  retries: 2
  delay: 5
  register: ansible_pdm_mailserver_key_success
  until: ansible_pdm_mailserver_key_success is succeeded
  with_items:
    # nginx
    - 7BD9BF62
    # rspamd
    - BF21E25E

- name: Add some repos
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
    - "deb http://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"
    - ppa:certbot/certbot

- name: Install necessities and nice-to-haves
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - cron
    - fail2ban
    - rspamd
    - nginx
    - libsasl2-modules
    - postfix
    - postfix-pcre
    - postfix-mysql
    - postgrey
    - sasl2-bin
    - mysql-client
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-managesieved
    - dovecot-mysql
    - dovecot-pop3d
    - opendkim
    - opendkim-tools
    - opendmarc
    - git
    - python-mysqldb
    - python-pip
    - certbot

- name: Upgrade Pip
  pip:
    extra_args: -U
    name: pip==18.1

- name: Install AWS CLI
  pip:
    extra_args: -U
    name: awscli==1.15.*

- name: Install MySQL
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - mysql-server
  when: ansible_pdm_mailserver_db_mysql_install

- name: Install Redis
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - redis-server
  when: ansible_pdm_mailserver_redis_install

- name: Create directory for LetsEncrypt configuration and certificates
  file:
    state: directory
    path: /etc/letsencrypt
    group: root
    owner: root

- name: Create directory for pre-renewal scripts
  file:
    state: directory
    path: /etc/letsencrypt/prerenew
    group: root
    owner: root

- name: Create directory for post-renewal scripts
  file:
    state: directory
    path: /etc/letsencrypt/postrenew
    group: root
    owner: root

- name: Create live directory for LetsEncrypt cron job
  file:
    state: directory
    path: /etc/letsencrypt/live
    group: root
    owner: root

- name: Modify permissions to allow ssl-cert group access
  file:
    path: /etc/letsencrypt/archive
    owner: root
    mode: 0750
    state: directory
  when: local_env is defined

- name: Install generate script for LetsEncrypt
  copy:
    src: letsencrypt-gencert
    dest: /etc/letsencrypt/letsencrypt-gencert
    owner: root
    group: root
    mode: 0755

- name: Install crontab entry for LetsEncrypt
  copy:
    src: etc_cron-daily_letsencrypt-renew
    dest: /etc/cron.daily/letsencrypt-renew
    owner: root
    group: root
    mode: 0755

- name: Create strong Diffie-Hellman group
  command: openssl dhparam -out /etc/ssl/private/dhparam2048.pem 2048
  args:
    creates: /etc/ssl/private/dhparam2048.pem

- name: Ensure Nginx site directories
  file:
    group: root
    mode: 0755
    owner: root
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available
  notify:
    - reload nginx

- name: Remove default Nginx site
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/conf.d/default
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify:
    - reload nginx

- name: Create Nginx config
  copy:
    dest: /etc/nginx/nginx.conf
    group: root
    mode: 622
    owner: root
    src: etc_nginx_nginx.conf
  notify:
    - reload nginx

- name: Create postfix maps directory
  file:
    path: /etc/postfix/maps
    state: directory
    owner: root
    group: root
  when: ansible_pdm_mailserver_header_privacy == 1

- name: Copy smtp_header_checks.pcre
  copy:
    src: etc_postfix_maps_smtp_header_checks.pcre
    dest: /etc/postfix/maps/smtp_header_checks.pcre
    owner: root
    group: root
  when: ansible_pdm_mailserver_header_privacy == 1

- name: Create vmail group
  group:
    name: vmail
    state: present
    gid: 5000

- name: Create vmail user
  user:
    name: vmail
    group: vmail
    state: present
    uid: 5000
    home: "{{ ansible_pdm_mailserver_mail_dir }}"
    shell: /usr/sbin/nologin

- name: Copy dovecot.conf into place
  copy:
    src: etc_dovecot_dovecot.conf
    dest: /etc/dovecot/dovecot.conf

- name: Update post-certificate-renewal task
  copy:
    content: "#!/bin/bash\n\nservice dovecot restart\n"
    dest: /etc/letsencrypt/postrenew/dovecot.sh
    mode: 0755
    owner: root
    group: root

- name: Create OpenDKIM config directory
  file:
    state: directory
    path: /etc/opendkim
    group: opendkim
    owner: opendkim

- name: Put opendkim.conf into place
  copy:
    src: etc_opendkim.conf
    dest: /etc/opendkim.conf
    owner: opendkim
    group: opendkim
  notify:
    - restart opendkim
    - restart postfix

- name: Patch opendmarc scripts (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742447)
  lineinfile:
    dest: "/usr/sbin/{{ item }}"
    regexp: '^require DBD::'
    line: 'require DBD::mysql;'
  with_items:
    - opendmarc-import
    - opendmarc-reports
    - opendmarc-params

- name: Patch opendmarc scripts part deux (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742447)
  lineinfile:
    dest: "/usr/sbin/{{ item }}"
    regexp: '^my \$dbscheme'
    line: 'my $dbscheme     = "mysql";'
  with_items:
    - opendmarc-reports
    - opendmarc-import

- name: Create OpenDMARC configuration directory
  file:
    state: directory
    path: /etc/opendmarc

- name: Copy OpenDMARC defaults file into place
  copy:
    src: etc_default_opendmarc
    dest: /etc/default/opendmarc
    owner: root
    group: root
  notify:
    - restart opendmarc
    - restart postfix

- name: Copy check-rbl into place
  copy:
    src: opt_check-rbl.pl
    dest: /opt/check-rbl.pl
    owner: root
    group: root

- name: Install nightly check-rbl cronjob
  cron:
    name: "check-rbl"
    hour: "2"
    minute: "0"
    job: "perl /opt/check-rbl.pl -i {{ ansible_default_ipv4.address }}"

- name: Create directory for mail autoconfiguration virtualhost
  file:
    state: directory
    path: /var/www/autoconfig
    group: www-data
    owner: root

- name: Create directory holding the autoconfig XML file
  file:
    state: directory
    path: /var/www/autoconfig/mail
    group: www-data
    owner: root
