---

- include: install.yml
  tags:
    - build

- name: Configure LetsEncrypt
  template:
    src: etc_letsencrypt_cli.conf.j2
    dest: /etc/letsencrypt/cli.conf
    owner: root
    group: root

- name: "Get an SSL certificate for {{ ansible_pdm_mailserver_domain }} from Let's Encrypt"
  script: "letsencrypt-gencert {{ ansible_pdm_mailserver_domain }}"
  args:
    creates: "/etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/privkey.pem"
  when: ansible_ssh_user != "vagrant"

### Several steps to install a self-signed wildcard key to support offline testing

- name: Create live directory for testing keys
  file:
    dest: "/etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ansible_ssh_user == "vagrant"

- name: Copy SSL wildcard private key for testing
  copy:
    src: wildcard_private.key
    dest: "/etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/privkey.pem"
    owner: root
    mode: 0640
  register: private_key
  when: ansible_ssh_user == "vagrant"

- name: Copy SSL public certificate into place for testing
  copy:
    src: wildcard_public_cert.crt
    dest: "/etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/cert.pem"
    group: root
    owner: root
    mode: 0644
  register: certificate
  when: ansible_ssh_user == "vagrant"

- name: Copy SSL CA combined certificate into place for testing
  copy:
    src: wildcard_ca.pem
    dest: "/etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/chain.pem"
    group: root
    owner: root
    mode: 0644
  register: ca_certificate
  when: ansible_ssh_user == "vagrant"

- name: Create a combined SSL cert for testing
  shell: "cat /etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/cert.pem /etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/chain.pem > /etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/fullchain.pem"
#  when: (private_key.changed or certificate.changed or ca_certificate.changed) and ansible_ssh_user == "vagrant"

- name: Set permissions on combined SSL public cert
  file:
    name: "/etc/letsencrypt/live/{{ ansible_pdm_mailserver_domain }}/fullchain.pem"
    mode: 0644
  when: ansible_ssh_user == "vagrant"


### Back to normal


#- include: dovecot.yml tags=dovecot
#- include: opendkim.yml tags=opendkim
#- include: opendmarc.yml tags=opendmarc
#- include: rspamd.yml tags=rspamd
#- include: checkrbl.yml tags=checkrbl
#- include: autoconfig.yml tags=autoconfig

- include: configure.yml
