---

- name: Install Postfix and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - libsasl2-modules
    - postfix
    - postfix-pcre
    - postfix-mysql
    - postgrey
    - python-psycopg2
    - sasl2-bin
  tags:
    - dependencies

- name: Create database for mail server
  mysql_db:
    login_host: localhost
    login_user: "{{ ansible_pdm_mailserver_db_admin_username }}"
    login_password: "{{ ansible_pdm_mailserver_db_admin_password }}"
    name: "{{ ansible_pdm_mailserver_db_database }}"
    state: present
  notify: import sql postfix

- name: Create database user for mail server
  mysql_user:
    login_host: localhost
    login_user: "{{ ansible_pdm_mailserver_db_admin_username }}"
    login_password: "{{ ansible_pdm_mailserver_db_admin_password }}"
    name: "{{ ansible_pdm_mailserver_db_username }}"
    password: "{{ ansible_pdm_mailserver_db_password }}"
    state: present
    host: "%"
    priv: "{{ ansible_pdm_mailserver_db_database }}.*:ALL"
  notify: import sql postfix

- name: Copy import.sql
  template:
    src: mailserver.sql.j2
    dest: /etc/postfix/import.sql
    owner: root
    group: root
    mode: 0600
  notify: import sql postfix

- name: Create postfix maps directory
  file:
    path: /etc/postfix/maps
    state: directory
    owner: root
    group: root
  when: ansible_pdm_mailserver_header_privacy == 1

- name: Copy smtp_header_checks.pcre
  copy:
    src: etc_postfix_maps_smtp_header_checks.pcre
    dest: /etc/postfix/maps/smtp_header_checks.pcre
    owner: root
    group: root
  when: ansible_pdm_mailserver_header_privacy == 1

- name: Copy main.cf
  template:
    src: etc_postfix_main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
  notify: restart postfix

- name: Copy master.cf
  copy:
    src: etc_postfix_master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
  notify: restart postfix

- name: Copy additional postfix configuration files
  template:
    src: "etc_postfix_{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    owner: root
    group: root
  with_items:
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
  notify: restart postfix
