---

- name: import database
  mysql_db:
    name: "{{ pdm_mailserver_mysql_database }}"
    state: import
    login_host: "{{ pdm_mailserver_mysql_host }}"
    login_user: "{{ pdm_mailserver_mysql_root_user }}"
    login_password: "{{ pdm_mailserver_mysql_root_password }}"
    target: /tmp/db_structure.sql

- name: reload dovecot
  become: yes
  service:
    name: dovecot
    state: reloaded

- name: restart dovecot
  become: yes
  service:
    name: dovecot
    state: restarted

- name: stop dovecot
  become: yes
  service:
    name: dovecot
    state: stopped

- name: start dovecot
  become: yes
  service:
    name: dovecot
    state: started

- name: reload postfix
  become: yes
  service:
    name: postfix
    state: reloaded

- name: restart postfix
  become: yes
  service:
    name: postfix
    state: restarted

- name: stop postfix
  become: yes
  service:
    name: postfix
    state: stopped

- name: start postfix
  become: yes
  service:
    name: postfix
    state: started
