#!/bin/bash
# We are using the "standalone" letsencrypt plugin, which runs its own
# webserver, so we need to temporarily free up the HTTP(S) ports by stopping
# Nginx.
service nginx stop
certbot certonly -c /etc/letsencrypt/cli.conf -d "autoconfig.${1}"
certbot certonly -c /etc/letsencrypt/cli.conf -d "srvr.${1}"
service nginx start
