#!/bin/bash
# We are using the "standalone" letsencrypt plugin, which runs its own
# webserver, so we need to temporarily free up the HTTP(S) ports by stopping
# Nginx.
service nginx stop
/root/letsencrypt/letsencrypt-auto certonly -c /etc/letsencrypt/cli.conf -d "autoconfig.${1}"
/root/letsencrypt/letsencrypt-auto certonly -c /etc/letsencrypt/cli.conf -d "${1}"
service nginx start
